/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartTitle: typeof import('./src/components/common/ChartTitle.vue')['default']
    ColumnChart: typeof import('./src/components/chart/ColumnChart.vue')['default']
    ComplateProgressChart: typeof import('./src/components/chart/ComplateProgressChart.vue')['default']
    copy: typeof import('./src/components/chart/PieChart copy.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PieChart: typeof import('./src/components/chart/PieChart.vue')['default']
    PieChartProportion: typeof import('./src/components/chart/PieChartProportion.vue')['default']
    ProjectComplate: typeof import('./src/components/ProjectComplate.vue')['default']
    ProjectPlan: typeof import('./src/components/ProjectPlan.vue')['default']
    ProjectTitle: typeof import('./src/components/common/ProjectTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowChart: typeof import('./src/components/chart/RowChart.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WaterFallChart: typeof import('./src/components/chart/WaterFallChart.vue')['default']
    WaterFallChart2: typeof import('./src/components/chart/WaterFallChart2.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    YearIncome: typeof import('./src/components/YearIncome.vue')['default']
  }
}
