/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartTitle: typeof import('./src/components/common/ChartTitle.vue')['default']
    ColumnChart: typeof import('./src/components/chart/ColumnChart.vue')['default']
    ComplateProgressChart: typeof import('./src/components/chart/ComplateProgressChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    HomeHeader: typeof import('./src/components/common/HomeHeader.vue')['default']
    MonthlyColumnChart: typeof import('./src/components/chart/MonthlyColumnChart.vue')['default']
    MonthlyTrend: typeof import('./src/components/MonthlyTrend.vue')['default']
    MonthlyTrendViewer: typeof import('./src/components/MonthlyTrendViewer.vue')['default']
    PieChart: typeof import('./src/components/chart/PieChart.vue')['default']
    PieChartProportion: typeof import('./src/components/chart/PieChartProportion.vue')['default']
    PlanProgressChart: typeof import('./src/components/chart/PlanProgressChart.vue')['default']
    ProjectComplate: typeof import('./src/components/ProjectComplate.vue')['default']
    ProjectComplete: typeof import('./src/components/ProjectComplete.vue')['default']
    ProjectPlan: typeof import('./src/components/ProjectPlan.vue')['default']
    ProjectTitle: typeof import('./src/components/common/ProjectTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowChart: typeof import('./src/components/chart/RowChart.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SuccessRate: typeof import('./src/components/chart/SuccessRate.vue')['default']
    WaterFallChart: typeof import('./src/components/chart/WaterFallChart.vue')['default']
    YearIncome: typeof import('./src/components/YearIncome.vue')['default']
  }
}
